version: "3.7"

services:
  tp01:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: tp01
    # env_file: .env
    # environment:
    #   - PGHOST=db
    #   - PGDATABASE=postgres
        # - PGHOST: "db"

    #  - DB_HOST=127.0.0.1
    #  - DB_PORT=5432
    ports:
      - "1234:1234"
    volumes:
      - .:/app/node/app
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
    networks:
      - tp01-network
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: tp01_db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgressql/data
    environment:
      PGPORT: 12345
      # PGHOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp01
    ports:
      - "12345:12345"
    networks:
      - tp01-network






networks:
  tp01-network:
      driver: local

volumes:
  data_postgres: {}
