version: "3"

services:
  tp01:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: tp01
    ports:
      - "1234:1234"
    volumes:
      - .:/app/node/app
    extra_hosts:
      - "host.docker.internal:172.0.0.1"
    networks:
      - tp01-network
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: tp01_db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp01
    ports:
      - "12345:5432"
    networks:
      - tp01-network










networks:
  tp01-network:
      # driver: bridge

volumes:
  data_postgres: {}
