version: "3"

services:
  tp01:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: tp01
    ports:
      - "1234:1234"
    volumes:
      - .:/app/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - tp01-network
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: tp01_db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp01
    ports:
      - "12345:5432"
    networks:
      - tp01-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #       PGADMIN_DEFAULT_PASSWORD: password
  #       PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 15432:80
  #   volumes:
  #     - pdadmin:/var/lib/pdadmin
  #   depends_on:
  #     - db
  #   networks:
  #     - tp01-network






networks:
  tp01-network:
      driver: bridge

volumes:
  data_postgres: {}
  pdadmin: {}